In [3]:
import numpy as np
input_set = np.array([  [0,1,0],
                        [0,0,1],
                        [1,1,0],
                        [1,1,0],
                        [1,1,1],
                        [0,1,1],
                        [0,1,0],
])

labels = np.array([[1,
                    0,
                    0,
                    1,
                    1,
                    0,
                    1,]])

labels = labels.reshape(7,1)

In [4]:
np.random.seed(42)
weights = np.random.rand(3,1)
bias = np.random.rand(1)
lr = 0.05

In [6]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [7]:
def sigmoid_derivative (x):
    return sigmoid(x)*(1-sigmoid(x))

In [8]:
inputs = input_set
print(inputs)

[[0 1 0]
 [0 0 1]
 [1 1 0]
 [1 1 0]
 [1 1 1]
 [0 1 1]
 [0 1 0]]


In [9]:
XW = np.dot(inputs, weights)+ bias
print(XW)

[[1.54937279]
 [1.33065243]
 [1.92391291]
 [1.92391291]
 [2.65590685]
 [2.28136673]
 [1.54937279]]


In [10]:
z = sigmoid(XW)
print(z)

[[0.82482312]
 [0.79094853]
 [0.87257414]
 [0.87257414]
 [0.93437412]
 [0.90732204]
 [0.82482312]]


In [11]:
error = z - labels
print(error)

[[-0.17517688]
 [ 0.79094853]
 [ 0.87257414]
 [-0.12742586]
 [-0.06562588]
 [ 0.90732204]
 [-0.17517688]]


In [12]:
print(error.sum())

2.0274392225222626


In [13]:
dcost = error
dpred = sigmoid_derivative(z)
z_del = dcost * dpred
inputs = input_set.T
weights = weights-lr*np.dot(inputs, z_del)

In [14]:
print(weights)

[[0.36746024]
 [0.93805208]
 [0.71487592]]


In [15]:
for num in z_del:
        bias = bias - lr*num

# Nilai bias baru
print(bias)

[0.57750768]
